export const handleLand = () => {};
export const formValues = {
  price: "",
  status: "",
  landmark: "",
  title: "",
  lga: "",
  city: "",
  bathroom: "",
  bedroom: "",
  streetname: "",
  city: "",
  latitude: "",
  longititude: "",
  description: "",
  videoUrl: "",
  videoUrl_2: "",
  videoUrl_3: "",
};
export const landUploadArray = [
  {
    _id: "323",
    type: "text",
    placeholder: "title",
    onChange: handleLand,
    name: "title",
    labelText: "title",
    value: formValues.title,
  },
  {
    _id: "323hd",
    type: "text",
    placeholder: "Landmark",
    onChange: handleLand,
    name: "landmark",
    labelText: "landmark",
    value: formValues.landmark,
  },
  {
    _id: "33423",
    type: "text",
    placeholder: "Streetname",
    onChange: handleLand,
    name: "streetname",
    labelText: "streetname",
    value: formValues.streetname,
  },
  {
    _id: "323dds",
    type: "number",
    placeholder: "Latitude",
    onChange: handleLand,
    name: "latitude",
    labelText: "latitude",
    value: formValues.latitude,
  },
  {
    _id: "323kws",
    type: "number",
    placeholder: "Longititude",
    onChange: handleLand,
    name: "longititude",
    labelText: "Longititude",
    value: formValues.longititude,
  },
  {
    _id: "323kwdids",
    type: "text",
    placeholder: "local government area",
    onChange: handleLand,
    name: "lga",
    labelText: "local government area",
    value: formValues.lga,
  },

  {
    _id: "323kwdids",
    type: "select",
    placeholder: "status",
    onChange: handleLand,
    name: "status",
    labelText: "status",
    value: formValues.status,
    helperText: "select property status",
    options: [
      {
        text: "FOR SALE",
        value: "FOR SALE",
      },
      {
        text: "FOR RENT",
        value: "FOR RENT",
      },
    ],
  },

  {
    _id: "323kwdids",
    type: "textarea",
    placeholder: "property description",
    onChange: handleLand,
    name: "description",
    labelText: "property description",
    value: formValues.description,
  },
];
